name: 'Setup Smithy CLI'
description: 'Install Smithy CLI for building the project'

runs:
  using: 'composite'
  steps:
    - name: Install Smithy CLI
      shell: bash
      env:
        SMITHY_VERSION: '1.61.0'
      run: |
        mkdir -p smithy-install/smithy
        curl -L https://github.com/smithy-lang/smithy/releases/download/${SMITHY_VERSION}/smithy-cli-linux-x86_64.zip -o smithy-install/smithy-cli-linux-x86_64.zip
        unzip -qo smithy-install/smithy-cli-linux-x86_64.zip -d smithy-install
        mv smithy-install/smithy-cli-linux-x86_64/* smithy-install/smithy
        sudo smithy-install/smithy/install
        smithy --version
