name: Test

on:
  push:
    branches-ignore:
    - 'development/**'

permissions:
  contents: read
  packages: write

jobs:
  lint:
    name: Lint and typecheck
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: TypeScript typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint

  test-mongodb-backend:
    name: Test with MongoDB backend
    runs-on: ubuntu-24.04
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Start Cloudserver with MongoDB backend
        run: docker compose -f .github/docker-compose.yml --profile mongo up -d --wait

      - name: Run MongoDB backend tests
        run: yarn test:mongo-backend

  test-metadata-backend:
    name: Test with Scality metadata backend
    runs-on: ubuntu-24.04
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Start Cloudserver with Scality metadata backend
        run: docker compose -f .github/docker-compose.yml --profile metadata up -d --wait

      - name: Wait for metadata to be ready
        run: |
          set -o pipefail
          bash .github/scripts/wait_for_local_port.bash 9000 40

      - name: Run metadata backend tests
        run: yarn test:metadata-backend

  test-backbeat-apis:
    name: Test backbeat apis
    runs-on: ubuntu-24.04
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Start Backbeat with CloudServer
        run: docker compose -f .github/docker-compose.yml --profile backbeat up -d --wait

      - name: Run backbeat apis tests
        run: yarn test:backbeat-apis
